spring.application.name=ingesta-layered-minimal
spring.jackson.deserialization.fail-on-unknown-properties=true

# Cuenta de Azure Storage donde se guardan las evidencias (sin claves, se autentica por Identidad Gestionada / az login)
azure.storage.account-name=sttransaccionesfase1
azure.storage.container-name=evidencias-financieras-privado

